services:
  ftps_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2121:2121"
      - "60010-60020:60010-60020"
    env_file: 
      - .env  
    environment:
      - PORT=2121
    volumes:
      - /ftp_server_implementation/image_storage:/mnt/vfs/image_storage # new line
    restart: always
    container_name: my_app_container
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2121/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
